version: '3'

services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - 8081:80

  supervisor:
    build: ./docker/php-fpm
    restart: always
    depends_on:
      - php-fpm
    volumes:
      - ./backend:/var/www:rw
      - ./docker/php-fpm/laravel-worker.conf:/etc/supervisord.conf
    command: supervisord

  redis:
    image: redis:7.0-alpine

  php-fpm:
    build: ./docker/php-fpm
    restart: always
    args:
      - UID=${UID}
      - GID=${GID}
    depends_on:
      - db
    volumes:
      - ./backend:/var/www:rw

#  php-cli-key-generate:
#    build: ./docker/php-cli
#    depends_on:
#      - php-fpm
#    volumes:
#      - ./backend:/var/www
#    working_dir: /var/www
#    command: php artisan key:generate
#
#  php-cli-migrate:
#    build: ./docker/php-cli
#    depends_on:
#      - php-fpm
#    volumes:
#    - ./backend:/var/www
#    working_dir: /var/www
#    command: php artisan migrate

#  composer:
#    image: composer:latest
#    depends_on:
#      - php-fpm
#    volumes:
#    - ./backend:/var/www
#    working_dir: /var/www
#    command: composer install

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
    - 6080:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: docker

  front:
    image: node:20-alpine
    volumes:
      - ./front:/var/www
    working_dir: /var/www
    command: sh -c "npm install && npm run build"