version: '3'

services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./backend:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - 8081:80

  php-fpm:
    build: ./docker/php-fpm
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend:/app

  php-cli-key-generate:
    image: php:8-cli-alpine
    depends_on:
      - php-fpm
    volumes:
      - ./backend:/app
    working_dir: /app
    command: php artisan key:generate

  php-cli-migrate:
    image: php:8-cli-alpine
    depends_on:
      - php-fpm
    volumes:
    - ./backend:/app
    working_dir: /app
    command: php artisan migrate

  composer:
    image: composer:latest
    depends_on:
      - php-fpm
    volumes:
    - ./backend:/app
    working_dir: /app
    command: composer install

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
    - 6080:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: docker
